/* Generated By:JJTree&JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package shixi1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 7;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 8;
  /** RegularExpression Id. */
  int HEX_LITERAL = 9;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int INT = 13;
  /** RegularExpression Id. */
  int RETURN = 14;
  /** RegularExpression Id. */
  int VOID = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int LETTER = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int COMMA = 20;
  /** RegularExpression Id. */
  int SEM = 21;
  /** RegularExpression Id. */
  int LFBRACKET = 22;
  /** RegularExpression Id. */
  int RFBRACKET = 23;
  /** RegularExpression Id. */
  int LBRACKET = 24;
  /** RegularExpression Id. */
  int RBRACKET = 25;
  /** RegularExpression Id. */
  int LRBRACKET = 26;
  /** RegularExpression Id. */
  int RRBRACKET = 27;
  /** RegularExpression Id. */
  int ADD = 28;
  /** RegularExpression Id. */
  int MUL = 29;
  /** RegularExpression Id. */
  int MINUS = 30;
  /** RegularExpression Id. */
  int DIVISOR = 31;
  /** RegularExpression Id. */
  int LESSTHAN = 32;
  /** RegularExpression Id. */
  int GREATERTHAN = 33;
  /** RegularExpression Id. */
  int EQUAL = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "\"if\"",
    "\"else\"",
    "\"int\"",
    "\"return\"",
    "\"void\"",
    "\"while\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\",\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"*\"",
    "\"-\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"%\"",
  };

}
