@startuml
start
switch (选择管理对象)
case ( 删除课程 )
  :输入课程ID;
  :确认删除;
  :更新数据库;
case ( 修改课程 )
  :输入课程ID;
  :查询数据库;
  :转入修改页面;
  :确认修改;
  :更新数据库;
case ( 增加课程 )
  :转入新增页面;
  :填写课程信息;
  :确认新增;
  :更新数据库;
endswitch
stop
@enduml
