package com.zhangyc.MiniCGrammar;

/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 5.0 */


public interface MyNewGrammarTreeConstants
{
    public int JJTSTART = 0;
    public int JJTSENTENCEBLOCK = 1;
    public int JJTSENTENCE = 2;
    public int JJTSHUNXU = 3;
    public int JJTSHENGMING = 4;
    public int JJTFUZHI = 5;
    public int JJTZIZENG = 6;
    public int JJTTIAOJIANYUJU = 7;
    public int JJTXUNHUAN = 8;
    public int JJTBASICBOOLEAN = 9;
    public int JJTYUBOOLEAN = 10;
    public int JJTBOOLEAN = 11;
    public int JJTTIAOJIAN = 12;
    public int JJTSWITCHCASE = 13;
    public int JJTGUANXIFU = 14;
    public int JJTBIAODASHI = 15;
    public int JJTEXPRESSION = 16;
    public int JJTADDITIVEEXPRESSION = 17;
    public int JJTMULTIPLICATIVEEXPRESSION = 18;
    public int JJTUNARYEXPRESSION = 19;
    public int JJTIDENTIFIER = 20;
    public int JJTINTEGER = 21;
    public int JJTRETURNSTATMENT = 22;
    public int JJTFLOAT = 23;


    public String[] jjtNodeName = {
            "Start",
            "SentenceBlock",
            "Sentence",
            "shunxu",
            "shengming",
            "fuzhi",
            "zizeng",
            "tiaojianyuju",
            "xunhuan",
            "BasicBoolean",
            "YuBoolean",
            "Boolean",
            "tiaojian",
            "SwitchCase",
            "guanxifu",
            "biaodashi",
            "Expression",
            "AdditiveExpression",
            "MultiplicativeExpression",
            "UnaryExpression",
            "Identifier",
            "Integer",
            "Returnstatment",
            "Float",
    };
}
/* JavaCC - OriginalChecksum=65dc1b49b8266c87c3d293408c05e29c (do not edit this line) */

