/* Generated By:JavaCC: Do not edit this line. miniCTreeConstants.java Version 5.0 */
package myPackage;

public interface miniCTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROCEDURE = 1;
  public int JJTFUNCTION = 2;
  public int JJTPARAMETER = 3;
  public int JJTSTATEMENTBLOCKS = 4;
  public int JJTSTATEMENT = 5;
  public int JJTCALLFUN = 6;
  public int JJTSEQSTATEMENT = 7;
  public int JJTSWITCHCASE = 8;
  public int JJTCASESTATE = 9;
  public int JJTDECLARSTATEMENT = 10;
  public int JJTASSIGNSTATEMENT = 11;
  public int JJTCONDSTATEMENT = 12;
  public int JJTLOGIC = 13;
  public int JJTLOGICAND = 14;
  public int JJTLOGICNOT = 15;
  public int JJTCONDITION = 16;
  public int JJTLOOPSTATEMENT = 17;
  public int JJTWHILE = 18;
  public int JJTDO_WHILE = 19;
  public int JJTFOR_LOOP = 20;
  public int JJTEXPRESSION = 21;
  public int JJTADDITIVEEXPRESSION = 22;
  public int JJTMULTIPLICATIVEEXPRESSION = 23;
  public int JJTUNARYEXPRESSION = 24;
  public int JJTIDENTIFIER = 25;
  public int JJTDEFINEID = 26;
  public int JJTINTEGER = 27;
  public int JJTFLOAT = 28;
  public int JJTSTARTKEY = 29;
  public int JJTDECLARKEY = 30;
  public int JJTRELATIONCHAR = 31;


  public String[] jjtNodeName = {
    "Start",
    "Procedure",
    "function",
    "Parameter",
    "StatementBlocks",
    "Statement",
    "callfun",
    "SeqStatement",
    "SwitchCase",
    "CaseState",
    "DeclarStatement",
    "AssignStatement",
    "CondStatement",
    "Logic",
    "LogicAnd",
    "LogicNot",
    "Condition",
    "LoopStatement",
    "While",
    "Do_While",
    "For_Loop",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "DefineId",
    "Integer",
    "Float",
    "StartKey",
    "DeclarKey",
    "RelationChar",
  };
}
/* JavaCC - OriginalChecksum=e3441d9588928d0bb75cda71de05efae (do not edit this line) */
