/* Generated By:JJTree&JavaCC: Do not edit this line. miniC.java */
package myPackage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import java.io.IOException;
import util.*;
import util.TokenTable;

public class miniC/*@bgen(jjtree)*/implements miniCTreeConstants, miniCConstants {/*@bgen(jjtree)*/
  protected static JJTminiCState jjtree = new JJTminiCState();public static TokenTable tokenTable = new TokenTable();

  public static VariableNameGenerator variableNameGenerator = new VariableNameGenerator();

  public static QTList qtList = new QTList();

  public static SimpleNode n;

  public static boolean errorflag=false;

  public static VariableTable varTable = new VariableTable();

  public static void begin(File file, int tag) throws FileNotFoundException, ParseException
  {
    FileInputStream fstream = new FileInputStream(file);
    if (tag != 0)
    {
      System.out.println(tag);
      ReInit(fstream);
    }
    else
    {
      new miniC(fstream);
    }
    n = miniC.Start();
  }

  public static void lexAnaly()
  {
    tokenTable.printTokenTable();
  }

  public static void syncTreePrint() throws IOException
  {
    File file = new File("./output/syncTree.txt");
        BufferedWriter out = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file, true)));
        out.write("");
        out.flush();
        out.close();
    n.dump("");
  }

  public static void QTListPrint()
  {
    qtList.printQTList();
  }
  
  public static void varPrint()
  {
    varTable.printList();
  }

  public static void main(String args []) throws FileNotFoundException
  {
      File file = new File("./Files/accept/func.txt");
    //    File file = new File("./Files/avaiable/boolean.c");
    //    
    //File file = new File("./Files/checkError/reDefine.c");
//    File file = new File("./Files/checkError/unDefine.c");
//    File file = new File("./Files/avaiable/test.c");
    FileInputStream fstream = new FileInputStream(file);
    new miniC(fstream);
    try
    {
      n = miniC.Start();
      n.dump("");
      tokenTable.printTokenTable();

      varTable.printList();
//      QTList.printQTList();

      System.out.println("Thank you.");
    }
    catch (Exception e)
    {
      System.out.println("Oops.");
      System.out.println(e.getMessage());
    }
  }

  static final public SimpleNode Start() throws ParseException {
 /*@bgen(jjtree) Start */
  SimpleNode jjtn000 = new SimpleNode(JJTSTART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      Procedure();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return jjtn000;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public void Procedure() throws ParseException {
 /*@bgen(jjtree) Procedure */
  SimpleNode jjtn000 = new SimpleNode(JJTPROCEDURE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INT:
        case FLOAT:
        case BOOL:
        case DOUBLE:
        case CHAR:
          ;
          break;
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        function();
      }
      t = StartKey();
      t = jj_consume_token(MAIN);
    tokenTable.addToken(t);
      t = jj_consume_token(LB);
    tokenTable.addToken(t);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INT:
        case FLOAT:
        case BOOL:
        case DOUBLE:
        case CHAR:
          ;
          break;
        default:
          jj_la1[1] = jj_gen;
          break label_2;
        }
        Parameter();
      }
      t = jj_consume_token(RB);
    tokenTable.addToken(t);
      t = jj_consume_token(LS);
    tokenTable.addToken(t);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INT:
        case WHILE:
        case FLOAT:
        case BOOL:
        case DOUBLE:
        case FOR:
        case IF:
        case CHAR:
        case DO:
        case SWITCH:
        case IDENTIFIER:
        case LS:
          ;
          break;
        default:
          jj_la1[2] = jj_gen;
          break label_3;
        }
        StatementBlocks();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case RETURN:
        jj_consume_token(RETURN);
        Identifier();
        jj_consume_token(SEMIC);
        break;
      default:
        jj_la1[3] = jj_gen;
        ;
      }
      t = jj_consume_token(RS);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    tokenTable.addToken(t);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void function() throws ParseException {
 /*@bgen(jjtree) function */
  SimpleNode jjtn000 = new SimpleNode(JJTFUNCTION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = DeclarKey();
      DefineId(t);
    tokenTable.addToken(t);
      t = jj_consume_token(LB);
    tokenTable.addToken(t);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INT:
        case FLOAT:
        case BOOL:
        case DOUBLE:
        case CHAR:
          ;
          break;
        default:
          jj_la1[4] = jj_gen;
          break label_4;
        }
        Parameter();
      }
      t = jj_consume_token(RB);
    tokenTable.addToken(t);
      t = jj_consume_token(LS);
    tokenTable.addToken(t);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INT:
        case WHILE:
        case FLOAT:
        case BOOL:
        case DOUBLE:
        case FOR:
        case IF:
        case CHAR:
        case DO:
        case SWITCH:
        case IDENTIFIER:
        case LS:
          ;
          break;
        default:
          jj_la1[5] = jj_gen;
          break label_5;
        }
        StatementBlocks();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case RETURN:
        jj_consume_token(RETURN);
        Identifier();
        jj_consume_token(SEMIC);
        break;
      default:
        jj_la1[6] = jj_gen;
        ;
      }
      t = jj_consume_token(RS);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    tokenTable.addToken(t);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void Parameter() throws ParseException {
 /*@bgen(jjtree) Parameter */
  SimpleNode jjtn000 = new SimpleNode(JJTPARAMETER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
  Token dt;
  boolean tag;
    try {
      dt = DeclarKey();
      tag = DefineId(dt);
    if (tag == false)
    {
    //      System.out.println(dt.beginLine + " " + dt.beginColumn + "  error Declar: " + dt.image);
    }
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[7] = jj_gen;
          break label_6;
        }
        t = jj_consume_token(COMMA);
      tokenTable.addToken(t);
        dt = DeclarKey();
        tag = DefineId(dt);
      if (tag == false)
      {
      //        System.out.println(dt.beginLine + " " + dt.beginColumn + "  error Declar: " + dt.image);
      }
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void StatementBlocks() throws ParseException {
 /*@bgen(jjtree) StatementBlocks */
  SimpleNode jjtn000 = new SimpleNode(JJTSTATEMENTBLOCKS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
      case WHILE:
      case FLOAT:
      case BOOL:
      case DOUBLE:
      case FOR:
      case IF:
      case CHAR:
      case DO:
      case SWITCH:
      case IDENTIFIER:
        Statement();
        break;
      case LS:
        t = jj_consume_token(LS);
      tokenTable.addToken(t);
        label_7:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case INT:
          case WHILE:
          case FLOAT:
          case BOOL:
          case DOUBLE:
          case FOR:
          case IF:
          case CHAR:
          case DO:
          case SWITCH:
          case IDENTIFIER:
          case LS:
            ;
            break;
          default:
            jj_la1[8] = jj_gen;
            break label_7;
          }
          StatementBlocks();
        }
        t = jj_consume_token(RS);
      jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
      tokenTable.addToken(t);
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
   if (jjtc000) {
     jjtree.clearNodeScope(jjtn000);
     jjtc000 = false;
   } else {
     jjtree.popNode();
   }
   if (jjte000 instanceof RuntimeException) {
     {if (true) throw (RuntimeException)jjte000;}
   }
   if (jjte000 instanceof ParseException) {
     {if (true) throw (ParseException)jjte000;}
   }
   {if (true) throw (Error)jjte000;}
    } finally {
   if (jjtc000) {
     jjtree.closeNodeScope(jjtn000, true);
   }
    }
  }

  static final public void Statement() throws ParseException {
 /*@bgen(jjtree) Statement */
  SimpleNode jjtn000 = new SimpleNode(JJTSTATEMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
      case FLOAT:
      case BOOL:
      case DOUBLE:
      case CHAR:
      case SWITCH:
      case IDENTIFIER:
        SeqStatement();
        break;
      case IF:
        CondStatement();
        break;
      case WHILE:
      case FOR:
      case DO:
        LoopStatement();
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void callfun() throws ParseException {
 /*@bgen(jjtree) callfun */
  SimpleNode jjtn000 = new SimpleNode(JJTCALLFUN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      jj_consume_token(IDENTIFIER);
      jj_consume_token(LB);
      jj_consume_token(IDENTIFIER);
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[11] = jj_gen;
          break label_8;
        }
        jj_consume_token(COMMA);
        jj_consume_token(IDENTIFIER);
      }
      jj_consume_token(RB);
      t = jj_consume_token(SEMIC);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    tokenTable.addToken(t);
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void SeqStatement() throws ParseException {
 /*@bgen(jjtree) SeqStatement */
  SimpleNode jjtn000 = new SimpleNode(JJTSEQSTATEMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
      case FLOAT:
      case BOOL:
      case DOUBLE:
      case CHAR:
      case IDENTIFIER:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INT:
        case FLOAT:
        case BOOL:
        case DOUBLE:
        case CHAR:
          DeclarStatement();
          break;
        case IDENTIFIER:
          AssignStatement();
          break;
        default:
          jj_la1[12] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        t = jj_consume_token(SEMIC);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    tokenTable.addToken(t);
        break;
      case SWITCH:
        SwitchCase();
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void SwitchCase() throws ParseException {
 /*@bgen(jjtree) SwitchCase */
  SimpleNode jjtn000 = new SimpleNode(JJTSWITCHCASE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(SWITCH);
                  tokenTable.addToken(t);
      t = jj_consume_token(LB);
             tokenTable.addToken(t);
      Identifier();
      t = jj_consume_token(RB);
             tokenTable.addToken(t);
      t = jj_consume_token(LS);
             tokenTable.addToken(t);
      CaseState();
      t = jj_consume_token(RS);
              jjtree.closeNodeScope(jjtn000, true);
              jjtc000 = false;
             tokenTable.addToken(t);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void CaseState() throws ParseException {
 /*@bgen(jjtree) CaseState */
  SimpleNode jjtn000 = new SimpleNode(JJTCASESTATE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t, t1;
    try {
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CASE:
          ;
          break;
        default:
          jj_la1[14] = jj_gen;
          break label_9;
        }
        t = jj_consume_token(CASE);
      tokenTable.addToken(t);
        t1 = jj_consume_token(INTEGER_LITERAL);
      tokenTable.addToken(t1);
        t = jj_consume_token(COLON);
      tokenTable.addToken(t);
        StatementBlocks();
      }
      t = jj_consume_token(DEFAULTT);
      t = jj_consume_token(COLON);
      StatementBlocks();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void DeclarStatement() throws ParseException {
 /*@bgen(jjtree) DeclarStatement */
  SimpleNode jjtn000 = new SimpleNode(JJTDECLARSTATEMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t, t2;
  boolean tag = true;
    try {
      t = DeclarKey();
      tag = DefineId(t);
    if (tag == false)
    {
    //      System.out.println(t.beginLine + " " + t.beginColumn + "  error Declar: " + t.image);
    }
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[15] = jj_gen;
          break label_10;
        }
        t2 = jj_consume_token(COMMA);
      tokenTable.addToken(t2);
        tag = DefineId(t);
      //      varTable.printList();
      if (tag == false)
      {
      //        System.out.println(t.beginLine + " " + t.beginColumn + "  error Declar: " + t.image);
      }
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void AssignStatement() throws ParseException {
 /*@bgen(jjtree) AssignStatement */
  SimpleNode jjtn000 = new SimpleNode(JJTASSIGNSTATEMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token op;
  Token first;
  String exp;
    try {
      first = Identifier();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 55:
        op = jj_consume_token(55);
      tokenTable.addToken(op);
        exp = Expression();
      QTInfo qt = new QTInfo(op.image, exp, "_", first.image);
      qtList.addQTInfo(qt);
        break;
      default:
        jj_la1[16] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LB:
        jj_consume_token(LB);
        jj_consume_token(IDENTIFIER);
        label_11:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case COMMA:
            ;
            break;
          default:
            jj_la1[17] = jj_gen;
            break label_11;
          }
          jj_consume_token(COMMA);
          jj_consume_token(IDENTIFIER);
        }
        jj_consume_token(RB);
        break;
      default:
        jj_la1[18] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void CondStatement() throws ParseException {
 /*@bgen(jjtree) CondStatement */
  SimpleNode jjtn000 = new SimpleNode(JJTCONDSTATEMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);ConditionValue chain = new ConditionValue();
  ConditionValue temp = new ConditionValue();
  int i;
  Token t;
    try {
      t = jj_consume_token(IF);
    tokenTable.addToken(t);
      t = jj_consume_token(LB);
    tokenTable.addToken(t);
    chain = Logic();
      t = jj_consume_token(RB);
    tokenTable.addToken(t);
    i = QTInfo.size + 1;
    chain.backpatchTrueChain(i);
      StatementBlocks();
    QTInfo qt = new QTInfo("J", "_", "_", "N");
    temp.mergeTrue(qt);
    qtList.addQTInfo(qt);
    i = QTInfo.size + 1;
    chain.backpatchFalseChain(i);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ELSE:
        t = jj_consume_token(ELSE);
      tokenTable.addToken(t);
        StatementBlocks();
      i = QTInfo.size + 1;
      temp.backpatchTrueChain(i);
        break;
      default:
        jj_la1[19] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public ConditionValue Logic() throws ParseException {
 /*@bgen(jjtree) Logic */
  SimpleNode jjtn000 = new SimpleNode(JJTLOGIC);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);int seq = 0;
  int tag = 0;
  Token t;
  ConditionValue chain = new ConditionValue();
  ConditionValue resChain = new ConditionValue();
  ConditionValue chain2 = new ConditionValue();
    try {
      chain = LogicAnd();
      label_12:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case OR:
          ;
          break;
        default:
          jj_la1[20] = jj_gen;
          break label_12;
        }
        t = jj_consume_token(OR);
      tokenTable.addToken(t);
      tag = 1;
      seq = QTInfo.size + 1;
      chain.backpatchFalseChain(seq);
        chain2 = LogicAnd();
      resChain = new ConditionValue();
      ExpressionType.merge(resChain.getFalseChain(), chain2.getFalseChain());
      ExpressionType.merge(chain2.getTrueChain(), chain.getTrueChain());
      ExpressionType.merge(resChain.getTrueChain(), chain2.getTrueChain());
      chain = resChain;
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    if (tag == 0)
    {if (true) return chain;}
    else
    {if (true) return resChain;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public ConditionValue LogicAnd() throws ParseException {
 /*@bgen(jjtree) LogicAnd */
  SimpleNode jjtn000 = new SimpleNode(JJTLOGICAND);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);int seq = 0;
  int tag = 0;
  Token t;
  ConditionValue chain = new ConditionValue();
  ConditionValue resChain = new ConditionValue();
  ConditionValue chain2 = new ConditionValue();
    try {
      chain = LogicNot();
      label_13:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AND:
          ;
          break;
        default:
          jj_la1[21] = jj_gen;
          break label_13;
        }
        t = jj_consume_token(AND);
      tokenTable.addToken(t);
      tag = 1;
      seq = QTInfo.size + 1;
      chain.backpatchTrueChain(seq);
        chain2 = LogicNot();
      resChain = new ConditionValue();
      ExpressionType.merge(resChain.getTrueChain(), chain2.getTrueChain());
      ExpressionType.merge(chain2.getFalseChain(), chain.getFalseChain());
      ExpressionType.merge(resChain.getFalseChain(), chain2.getFalseChain());
      chain = resChain;
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    if (tag == 0)
    {if (true) return chain;}
    else
    {if (true) return resChain;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public ConditionValue LogicNot() throws ParseException {
 /*@bgen(jjtree) LogicNot */
  SimpleNode jjtn000 = new SimpleNode(JJTLOGICNOT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);ConditionValue chain = new ConditionValue();
  ConditionValue chain1 = new ConditionValue();
  Token t;
    try {
      label_14:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INTEGER_LITERAL:
        case FLOAT_LITERAL:
        case TRUE:
        case FALSE:
        case IDENTIFIER:
        case LB:
        case UN:
          ;
          break;
        default:
          jj_la1[22] = jj_gen;
          break label_14;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INTEGER_LITERAL:
        case FLOAT_LITERAL:
        case TRUE:
        case FALSE:
        case IDENTIFIER:
        case LB:
          chain = Condition();
          break;
        case UN:
          t = jj_consume_token(UN);
        tokenTable.addToken(t);
          chain1 = Condition();
        chain.setTrueChain(chain1.getFalseChain());
        chain.setFalseChain(chain1.getTrueChain());
          break;
        default:
          jj_la1[23] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return chain;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public ConditionValue Condition() throws ParseException {
 /*@bgen(jjtree) Condition */
  SimpleNode jjtn000 = new SimpleNode(JJTCONDITION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);int tag = 0;
  String first;
  String middle;
  String rop;
  ConditionValue chain = new ConditionValue();
    try {
      first = Expression();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LESS:
      case LESSN:
      case GREAT:
      case GREATN:
      case EQU:
      case NOTEQU:
        rop = RelationChar();
        middle = Expression();
      QTInfo qt1 = new QTInfo("J" + rop, first, middle, "N");
      QTInfo qt2 = new QTInfo("J", "_", "_", "N");
      chain.mergeTrue(qt1);
      chain.mergeFalse(qt2);
      qtList.addQTInfo(qt1);
      qtList.addQTInfo(qt2);
      tag = 1;
        break;
      default:
        jj_la1[24] = jj_gen;
        ;
      }
    if (tag == 0)
    {
      QTInfo qt1 = new QTInfo("JNZ", first, "_", "N");
      QTInfo qt2 = new QTInfo("J", "_", "_", "N");
      chain.mergeTrue(qt1);
      chain.mergeFalse(qt2);
      qtList.addQTInfo(qt1);
      qtList.addQTInfo(qt2);
    }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return chain;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public void LoopStatement() throws ParseException {
 /*@bgen(jjtree) LoopStatement */
  SimpleNode jjtn000 = new SimpleNode(JJTLOOPSTATEMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WHILE:
        While();
        break;
      case DO:
        Do_While();
        break;
      case FOR:
        For_Loop();
        break;
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void While() throws ParseException {
 /*@bgen(jjtree) While */
  SimpleNode jjtn000 = new SimpleNode(JJTWHILE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
  int seq = 0, tag;
  ConditionValue chain;
  ConditionValue temp = new ConditionValue();
    try {
      t = jj_consume_token(WHILE);
    tokenTable.addToken(t);
      t = jj_consume_token(LB);
    tokenTable.addToken(t);
    tag = qtList.QTList.size() + 1;
      chain = Logic();
      t = jj_consume_token(RB);
    tokenTable.addToken(t);
      t = jj_consume_token(LS);
    //    System.out.println(Integer.toString(tag));
    tokenTable.addToken(t);
    seq = QTInfo.size + 1;
    chain.backpatchTrueChain(seq);
      label_15:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INT:
        case WHILE:
        case FLOAT:
        case BOOL:
        case DOUBLE:
        case FOR:
        case IF:
        case CHAR:
        case DO:
        case SWITCH:
        case IDENTIFIER:
        case LS:
          ;
          break;
        default:
          jj_la1[26] = jj_gen;
          break label_15;
        }
        StatementBlocks();
      }
      t = jj_consume_token(RS);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    tokenTable.addToken(t);
    QTInfo qt = new QTInfo("J", "_", "_", Integer.toString(tag));
    qtList.addQTInfo(qt);
    seq = QTInfo.size + 1;
    chain.backpatchFalseChain(seq);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void Do_While() throws ParseException {
 /*@bgen(jjtree) Do_While */
  SimpleNode jjtn000 = new SimpleNode(JJTDO_WHILE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
  int seq, tag;
  ConditionValue chain;
    try {
      t = jj_consume_token(DO);
    tokenTable.addToken(t);
      t = jj_consume_token(LS);
    tokenTable.addToken(t);
    tag = qtList.QTList.size() + 1;
      label_16:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INT:
        case WHILE:
        case FLOAT:
        case BOOL:
        case DOUBLE:
        case FOR:
        case IF:
        case CHAR:
        case DO:
        case SWITCH:
        case IDENTIFIER:
        case LS:
          ;
          break;
        default:
          jj_la1[27] = jj_gen;
          break label_16;
        }
        StatementBlocks();
      }
      t = jj_consume_token(RS);
    tokenTable.addToken(t);
      t = jj_consume_token(WHILE);
    tokenTable.addToken(t);
      t = jj_consume_token(LB);
    tokenTable.addToken(t);
      chain = Logic();
//    QTInfo qt = new QTInfo("J", "_", "_", Integer.toString(tag));
//    QTList.addQTInfo(qt);
    seq = QTInfo.size + 1;
    chain.backpatchFalseChain(seq);
    chain.backpatchTrueChain(tag);
      t = jj_consume_token(RB);
    tokenTable.addToken(t);
      t = jj_consume_token(SEMIC);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    tokenTable.addToken(t);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void For_Loop() throws ParseException {
 /*@bgen(jjtree) For_Loop */
  SimpleNode jjtn000 = new SimpleNode(JJTFOR_LOOP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
  int seq, tag;
  ConditionValue chain;
    try {
      t = jj_consume_token(FOR);
    tokenTable.addToken(t);
      t = jj_consume_token(LB);
    tokenTable.addToken(t);
      AssignStatement();
      t = jj_consume_token(SEMIC);
    tokenTable.addToken(t);
      chain = Logic();
      jj_consume_token(SEMIC);
    tokenTable.addToken(t);
      AssignStatement();
      jj_consume_token(RB);
    tokenTable.addToken(t);
    seq = QTInfo.size + 1;
    chain.backpatchTrueChain(seq);
    tag = qtList.QTList.size() + 1;
      StatementBlocks();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    QTInfo qt = new QTInfo("J", "_", "_", Integer.toString(tag));
    qtList.addQTInfo(qt);
    seq = QTInfo.size + 1;
    chain.backpatchFalseChain(seq);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public String Expression() throws ParseException {
 /*@bgen(jjtree) Expression */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String exp;
    try {
      exp = AdditiveExpression();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return exp;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public String AdditiveExpression() throws ParseException {
 /*@bgen(jjtree) AdditiveExpression */
  SimpleNode jjtn000 = new SimpleNode(JJTADDITIVEEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String first;
  String middle;
  String newTemp;
  Token op;
    try {
      first = MultiplicativeExpression();
    newTemp = first;
      label_17:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ADD:
        case SUB:
          ;
          break;
        default:
          jj_la1[28] = jj_gen;
          break label_17;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ADD:
          op = jj_consume_token(ADD);
          break;
        case SUB:
          op = jj_consume_token(SUB);
          break;
        default:
          jj_la1[29] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      tokenTable.addToken(op);
        middle = MultiplicativeExpression();
      newTemp = variableNameGenerator.genVariableName();
      QTInfo qt = new QTInfo(op.image, first, middle, newTemp);
      qtList.addQTInfo(qt);
      first = newTemp;
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return newTemp;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public String MultiplicativeExpression() throws ParseException {
 /*@bgen(jjtree) MultiplicativeExpression */
  SimpleNode jjtn000 = new SimpleNode(JJTMULTIPLICATIVEEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String first;
  String middle;
  String newTemp;
  Token op;
    try {
      first = UnaryExpression();
    newTemp = first;
      label_18:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MULT:
        case DIV:
        case MOD:
          ;
          break;
        default:
          jj_la1[30] = jj_gen;
          break label_18;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MULT:
          op = jj_consume_token(MULT);
          break;
        case DIV:
          op = jj_consume_token(DIV);
          break;
        case MOD:
          op = jj_consume_token(MOD);
          break;
        default:
          jj_la1[31] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      tokenTable.addToken(op);
        middle = UnaryExpression();
      newTemp = variableNameGenerator.genVariableName();
      QTInfo qt = new QTInfo(op.image, first, middle, newTemp);
      qtList.addQTInfo(qt);
      first = newTemp;
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return newTemp;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public String UnaryExpression() throws ParseException {
 /*@bgen(jjtree) UnaryExpression */
  SimpleNode jjtn000 = new SimpleNode(JJTUNARYEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String exp;
  Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LB:
        t = jj_consume_token(LB);
        tokenTable.addToken(t);
        exp = Expression();
        t = jj_consume_token(RB);
        tokenTable.addToken(t);
        break;
      case IDENTIFIER:
        t = Identifier();
      exp = t.image;
        break;
      case INTEGER_LITERAL:
        t = Integer();
      exp = t.image;
        break;
      case TRUE:
        t = jj_consume_token(TRUE);
      tokenTable.addToken(t);
      exp = t.image;
        break;
      case FALSE:
        t = jj_consume_token(FALSE);
      tokenTable.addToken(t);
      exp = t.image;
        break;
      case FLOAT_LITERAL:
        t = Float();
      exp = t.image;
        break;
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return exp;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public Token Identifier() throws ParseException {
 /*@bgen(jjtree) Identifier */
  SimpleNode jjtn000 = new SimpleNode(JJTIDENTIFIER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(IDENTIFIER);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    if (varTable.canInsert(t.image) == false) //表示该标识符已经声明
    {
      tokenTable.addToken(t);
      {if (true) return t;}
    }
    else
    {
      String temp="Line: " + t.beginLine + " Column:" + t.beginColumn + " \u672a\u5b9a\u4e49\u53d8\u91cf: " + t.image;
        File error = new File("./output/error.txt");
        FileWriter fileWriter = null;
                try {
                        fileWriter = new FileWriter(error);
                } catch (IOException e) {
                        // TODO 自动生成的 catch 块
                        e.printStackTrace();
                }
        try {
                        fileWriter.write(temp);
                } catch (IOException e) {
                        // TODO 自动生成的 catch 块
                        e.printStackTrace();
                }
        try {
                        fileWriter.flush();
                } catch (IOException e) {
                        // TODO 自动生成的 catch 块
                        e.printStackTrace();
                }
        try {
                        fileWriter.close();
                } catch (IOException e) {
                        // TODO 自动生成的 catch 块
                        e.printStackTrace();
                }
        errorflag=true;
      {if (true) return t;}
    }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public boolean DefineId(Token t) throws ParseException {
 /*@bgen(jjtree) DefineId */
  SimpleNode jjtn000 = new SimpleNode(JJTDEFINEID);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token id;
    try {
      id = jj_consume_token(IDENTIFIER);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    //    varTable.printList();
    if (varTable.canInsert(id.image))
    {
      varTable.insertVar(id.image, t.image);
      tokenTable.addToken(id);
      {if (true) return true;}
    }
    String temp="Line: " + id.beginLine + " Column: " + id.beginColumn + " \u91cd\u590d\u5b9a\u4e49\u53d8\u91cf: " + id.image;
        File error = new File("./output/error.txt");
        FileWriter fileWriter = null;
		try {
			fileWriter = new FileWriter(error);
		} catch (IOException e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
		}
        try {
			fileWriter.write(temp);
		} catch (IOException e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
		}
        try {
			fileWriter.flush();
		} catch (IOException e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
		}
        try {
			fileWriter.close();
		} catch (IOException e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
		}
        errorflag=true;
    {if (true) return false;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public Token Integer() throws ParseException {
 /*@bgen(jjtree) Integer */
  SimpleNode jjtn000 = new SimpleNode(JJTINTEGER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(INTEGER_LITERAL);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    tokenTable.addToken(t);
    {if (true) return t;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public Token Float() throws ParseException {
 /*@bgen(jjtree) Float */
  SimpleNode jjtn000 = new SimpleNode(JJTFLOAT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(FLOAT_LITERAL);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    tokenTable.addToken(t);
    {if (true) return t;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public Token StartKey() throws ParseException {
 /*@bgen(jjtree) StartKey */
  SimpleNode jjtn000 = new SimpleNode(JJTSTARTKEY);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VOID:
        t = jj_consume_token(VOID);
        break;
      case INT:
        t = jj_consume_token(INT);
        break;
      default:
        jj_la1[33] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    tokenTable.addToken(t);
    {if (true) return t;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public Token DeclarKey() throws ParseException {
 /*@bgen(jjtree) DeclarKey */
  SimpleNode jjtn000 = new SimpleNode(JJTDECLARKEY);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
        t = jj_consume_token(INT);
        break;
      case FLOAT:
        t = jj_consume_token(FLOAT);
        break;
      case CHAR:
        t = jj_consume_token(CHAR);
        break;
      case DOUBLE:
        t = jj_consume_token(DOUBLE);
        break;
      case BOOL:
        t = jj_consume_token(BOOL);
        break;
      default:
        jj_la1[34] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    tokenTable.addToken(t);
    {if (true) return t;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final public String RelationChar() throws ParseException {
 /*@bgen(jjtree) RelationChar */
  SimpleNode jjtn000 = new SimpleNode(JJTRELATIONCHAR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token rop;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LESS:
        rop = jj_consume_token(LESS);
        break;
      case LESSN:
        rop = jj_consume_token(LESSN);
        break;
      case GREAT:
        rop = jj_consume_token(GREAT);
        break;
      case GREATN:
        rop = jj_consume_token(GREATN);
        break;
      case EQU:
        rop = jj_consume_token(EQU);
        break;
      case NOTEQU:
        rop = jj_consume_token(NOTEQU);
        break;
      default:
        jj_la1[35] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    tokenTable.addToken(rop);
    {if (true) return rop.image;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public miniCTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[36];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x839000,0x839000,0x8c8fb000,0x200000,0x839000,0x8c8fb000,0x200000,0x0,0x8c8fb000,0x8c8fb000,0x8c8fb000,0x0,0x80839000,0x88839000,0x10000000,0x0,0x0,0x0,0x0,0x100000,0x0,0x0,0x83000180,0x83000180,0x0,0x4042000,0x8c8fb000,0x8c8fb000,0x0,0x0,0x0,0x0,0x83000180,0x5000,0x839000,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x10,0x0,0x0,0x10,0x0,0x100000,0x10,0x10,0x0,0x100000,0x0,0x0,0x0,0x100000,0x800000,0x100000,0x4,0x0,0x1000,0x800,0x2004,0x2004,0xfc000,0x0,0x10,0x10,0xc0,0xc0,0x700,0x700,0x4,0x0,0x0,0xfc000,};
   }

  /** Constructor with InputStream. */
  public miniC(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public miniC(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new miniCTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 36; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 36; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public miniC(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new miniCTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 36; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 36; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public miniC(miniCTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 36; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(miniCTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 36; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[56];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 36; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 56; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
