/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package p2;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSENTENCEBLOCK = 1;
  public int JJTSENTENCE = 2;
  public int JJTSHUNXU = 3;
  public int JJTSHENGMING = 4;
  public int JJTFUZHI = 5;
  public int JJTTIAOJIANYUJU = 6;
  public int JJTXUNHUAN = 7;
  public int JJTTIAOJIAN = 8;
  public int JJTBIAODASHI = 9;
  public int JJTGUANXIFU = 10;
  public int JJTEXPRESSION = 11;
  public int JJTADDITIVEEXPRESSION = 12;
  public int JJTMULTIPLICATIVEEXPRESSION = 13;
  public int JJTUNARYEXPRESSION = 14;
  public int JJTIDENTIFIER = 15;
  public int JJTINTEGER = 16;


  public String[] jjtNodeName = {
    "Start",
    "SentenceBlock",
    "Sentence",
    "shunxu",
    "shengming",
    "fuzhi",
    "tiaojianyuju",
    "xunhuan",
    "tiaojian",
    "biaodashi",
    "guanxifu",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=2642ad84af1e369c6581938fb6132f66 (do not edit this line) */
